/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;

public class HuffmanCoding {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
    }
}
